### ISSUE TITLE
CommonJS plugin conflicting with esbuild plugin?

### ISSUE THREAD

**Issue by jimsimon** [modernweb-dev/web#1333]
I'm running into an issue where enabling the rollup commonjs plugin is breaking my app.

My config file is at: https://github.com/jimsimon/sports-app/blob/login/packages/ui/server.config.mjs

Commenting out the commonjs plugin (lines 12-16) results in everything rendering fine (bypassing the stuff that needs it for now). Leaving the plugin enabled results in:
![image](https://user-images.githubusercontent.com/156367/109777063-49b65700-7bd1-11eb-8518-e8fea8762d6f.png)

If I enable the code that needs graphql-tag and don't use the commonjs plugin, then I get:
![image](https://user-images.githubusercontent.com/156367/109777230-7bc7b900-7bd1-11eb-9fa7-e3086f67e963.png)

I'm a little confused as to what's happening here. I'm not sure if I'm hitting some sort of bug or if I've configured something incorrectly. I searched through some other issues and noticed a few other people (seemingly) successfully using graphql-tag with the commonjs plugin.

Any thoughts on how I can get things working?

**Comment by jimsimon** [comment]
I ended up getting this to work by specifying `rootDir: '../../'` in my config since I'm in a monorepo. It seems like the rollup commonjs plugin doesn't handle monorepos very well.

**Comment by rbquantori** [comment]
Just in case someone else have the same problem, here's how I solved CommonJS modules problem for `@web/test-runner` in `web-test-runner.config.mjs`:
```js
    plugins: [
        commonjs({
            include: ['**/node_modules/debounce/index.js'],
        }),
        esbuildPlugin({
            ts: true,
            tsconfig: './tsconfig.json',
        }),
    ],
    files: 'src/**/*.spec.ts',
};
```
The reason I had to add `**` before `node_modules` is because inside rollup's matcher it matches against full path, while the test-runner (and under the hood, `@web/dev-server` as far as I understand) gives it this `/__wds-outside-root/2/...` stuff.

**Comment by bashmish** [comment]
> Just in case someone else have the same problem, here's how I solved CommonJS modules problem for `@web/test-runner` in `web-test-runner.config.mjs`:
> 
> ```js
> export default {
>     plugins: [
>         commonjs({
>             include: ['**/node_modules/debounce/index.js'],
>         }),
>         esbuildPlugin({
>             ts: true,
>             tsconfig: './tsconfig.json',
>         }),
>     ],
>     files: 'src/**/*.spec.ts',
> };
> ```
> 
> The reason I had to add `**` before `node_modules` is because inside rollup's matcher it matches against full path, while the test-runner (and under the hood, `@web/dev-server` as far as I understand) gives it this `/__wds-outside-root/2/...` stuff.

Thanks for a detailed example and explanation, this is a good workaround I think.

Just a little extra background about why this is needed.
I saw this happening in the modern-web's own monorepo here, e.g. when testing `packages/storybook-builder`, because I think the subpackage tests are run with a project root set to `packages/%name%`, but the `node_modules` are deduped and located in the monorepo root, which is an "outside root" dir from the `packages/%name%` point of view.

Maybe `commonjs` plugin should take this into consideration when matching paths, but setting `include: ['**/node_modules/debounce/index.js'],` is not a mistake either in this case, as you are basically saying that it doesn't matter if I use dedupe root node_modules or subpackage specific ones, I want to have the CommonsJS package to be handled correctly.
