### ISSUE TITLE
[dev-server-storybook] Lazy load import is not working in build-storybook

### ISSUE THREAD

**Issue by Rajkumar-MP** [modernweb-dev/web#1336]
In my web component development, we have a lazy load component imports, its working fine in normal storybook run, but when we try to do the build, its not working, its try to render those files from the base root path.

In Below code, we are rendering the locale file based on the language.
```js
static get localizeNamespaces() {
    return [
      { 'sample-toggle': locale => import(`./translations/${locale}.js`) },
      ...super.localizeNamespaces,
    ];
  }
```

when we run through static storybook file, getting error like this
![image](https://user-images.githubusercontent.com/2493213/110061460-a2caea00-7d8d-11eb-8df9-c3da60aa15af.png)

**Comment by LarsDenBakker** [comment]
Rollup cannot evaluate expressions like this, since the `locale` variable could contain anything you could import anything on the file system.

There is a rollup plugin that adds limited support for evaluating dynamic imports with expression as a glob: https://www.npmjs.com/package/@rollup/plugin-dynamic-import-vars
