### ISSUE TITLE
Test runner generates coverage only for the files that are being tested

### ISSUE THREAD

**Issue by GeorgeTailor** [modernweb-dev/web#1348]
My setup is as follows:
sure, `web-test-runner.config.js`:
```
process.env.NODE_ENV = 'test';
module.exports = {
	plugins: [require('@snowpack/web-test-runner-plugin')()],
	coverage: true,
	coverageConfig: {
		report: true,
		reportDir: 'test-coverage',
		threshold: {
			statements: 20,
			branches: 20,
			functions: 20,
			lines: 20,
		},
		exclude: [
			'**/*/_snowpack/**/*',
			'**/*.test.js',
		],
	},
};
```
and in `package.json`:
```
"test": "web-test-runner ./src/**/*.test.tsx --coverage --port 1234"
```

Files that are not tested are not included in the final coverage report.

**Comment by Westbrook** [comment]
If you're not using the files in your tests, then they're not "uncovered". Only code that is actually loaded into the test context can be counted this way.

You _might_ be able to get this result by importing all of your app code into one of your tests files, but I'm not sure what sort of intervening tree shaking that Snowpack might be doing in such a context.

**Comment by GeorgeTailor** [comment]
IMO the test runner should be responsible for including everything. Currently, there is no way to tell it otherwise, which makes `--coverage` option negligible, since it does not show the full picture of the project test coverage.

**Comment by Westbrook** [comment]
In that case, how would you expect to provide to the testing context the files that you expect to be "covered"?

**Comment by LarsDenBakker** [comment]
It would be nice to be able to provide a glob of files to include in the coverage. It's harder to do with WTR, since the coverage files are instrumented and tracked in the browser. Karma had the same issue. It's easier for node js test runners like Jest. 

We would need to load a page in the browser that only load all the included files. Not sure if that would work for snowpack, since there is some build magic that it does.
