### ISSUE TITLE
Uncovered branches when files are loaded multiple times

### ISSUE THREAD

**Issue by MathieuPuech** [modernweb-dev/web#1468]
I've added on the lit-element example-project the reproduction of the issue
https://github.com/MathieuPuech/example-projects/tree/bug-coverage-fusion/lit-element

The issue is here:
![image](https://user-images.githubusercontent.com/9367152/119181232-4d72b080-ba3f-11eb-9056-4d98bd9ee26e.png)

This branch is covered by the tests in my-other-element.test.js but uncovered because of my-element.test.js

It seems that there is some fusion of coverage done in WTR removing coverage of covered branches.

**Comment by jvdsande** [comment]
Looking into this, at least for the specific case in @MathieuPuech's reproduction branch, the problem seems to come from this fix: https://github.com/istanbuljs/istanbuljs/issues/531#issuecomment-656826893

If I comment out the call to `addMissingCoverageItems` in `getTestCoverage`, then I get the expected 100%.

I looked through the 3 issues listed in the comments for `addingMissingCoverageItems`, and for now I can't really get my head around exactly what is going on. But definitely it seems like this code flags branches as uncovered in order to fill gaps between reports of multiple sessions, and this messes things up during the merge of sessions by libCoverage.

**Comment by jvdsande** [comment]
After further investigation, there seems to be some simplification happening at V8 or V8-to-instanbul side on sub-branches when both the sub-branch and the parent branch are covered.

## Suite-by-suite coverage analysis

Taking this faulty snippet: 

```js
  __click(bool) {
    this.hasBeenClicked = bool ?
      // This branch should be covered
      true : false;
  }
```

This is located from lines 15 to 19 as seen in the screenshot above.

Running the test case for MyElement.js (the one that does not cover everything), we get the following coverage:

![image](https://user-images.githubusercontent.com/12484011/122666585-7907c880-d1ae-11eb-8964-666bf7b23373.png)

So the parent branch (`__click` function scope) is covered, but a sub-branch (`bool === true` in ternary) is not covered (already here we see kind of a wacky reporting from V8 or at least in the V8-to-istanbul conversion, as the uncovered branch is not entirely reported, it should also cover the start of line 18 up until the `:`. This is an issue in the HTML rendered it seems, because the report correctly states the end of the branch at line 18 column 10)

This coverage is depicted with the following branches in the branchMap:

**Branch 3 - `__click` function scope** 

```json
"3": {
    "type": "branch",
    "line": 15,
    "loc": {
      "start": {
        "line": 15,
        "column": 2
      },
      "end": {
        "line": 19,
        "column": 3
      }
    },
    "locations": [
      {
        "start": {
          "line": 15,
          "column": 2
        },
        "end": {
          "line": 19,
          "column": 3
        }
      }
    ]
  }
```

And of course this is flagged as covered (`"3": [1]` in the coverage index)

**Branch 4 - ternary truthy statement**

```json
"4": {
    "type": "branch",
    "line": 16,
    "loc": {
      "start": {
        "line": 16,
        "column": 31
      },
      "end": {
        "line": 18,
        "column": 10
      }
    },
    "locations": [
      {
        "start": {
          "line": 16,
          "column": 31
        },
        "end": {
          "line": 18,
          "column": 10
        }
      }
    ]
  }
```

Here this branch is reported as uncovered, which is indeed the case (`"4": [0]` in the coverage index).

In the full coverage report we can see that the falsy branch of the ternary is not reported at all. It gets included in the upper scope branch I guess, since only the uncovered is deemed relevant.

Now, what happens when we run only the MyOtherElement.js test suite? This one covers all the branches:

![image](https://user-images.githubusercontent.com/12484011/122666872-216a5c80-d1b0-11eb-921c-702c32bb185b.png)

 But in the report we only get:

```json
  "4": {
    "type": "branch",
    "line": 21,
    "loc": {
      "start": {
        "line": 21,
        "column": 2
      },
      "end": {
        "line": 25,
        "column": 3
      }
    },
    "locations": [
      {
        "start": {
          "line": 21,
          "column": 2
        },
        "end": {
          "line": 25,
          "column": 3
        }
      }
    ]
  }
```

Which corresponds to the `__click` function scope, with coverage index reporting `"4": [1]` (covered)

In the full report we have no information about the sub-branch, as it gets "included" in the fact that the parent branch is covered, and no special case is to be reported otherwise.

## Merging those two reports

When merging those two reports, the sub-branch is detected in one suite (uncovered), and absent in the other suite. The `addingMissingCoverageItems` falsely assumes that the branch is therefore uncovered since absent, and adds an uncovered entry for the second test suite.

## Possible solution

Since the behaviour of either V8 coverage or at least V8-to-instanbul seems to ignore sub-branches when a parent branch is fully covered, the behaviour of `addingMissingCoverageItems` should match this expectation. Instead of defaulting all unknown branches to "uncovered", it should check for the smallest encompassing branch, and use its coverage instead.

However I don't know how fool-proof this solution is, since _not all sub-branches are removed from the report_. In both the reports, we have an an all-encompassing "branch" reported that covers the whole file, and is indeed reported as "covered", but does not make the other branches disappear.
