### ISSUE TITLE
[Storybook] a wds builder?

### ISSUE THREAD

**Issue by Westbrook** [modernweb-dev/web#2025]
Should the future of WDS Storybook be a Storybook builder? 

https://storybook.js.org/docs/react/builders/builder-api

Vite copied much of what WDS is, seems only fair to copy some of what it is. This may also clear up issues around typing and plug-in usage in Storybook Prebuilt while maintaining many of the wins from pushing the project to begin with. 

Thoughts?

**Comment by Westbrook** [comment]
@bashmish is doing some interesting work in this area at https://github.com/bashmish/storybook-builder-wds. I'm having a little trouble getting it set up, but it's getting close!

**Comment by bashmish** [comment]
@Westbrook hey! I've been on it for a while now, happy to help you set it up. It's currently an early phase of development, but basic stories functionality and official addons should be working in serve. The static build is coming - check out this branch https://github.com/bashmish/storybook-builder-wds/tree/feat/build for the latest updates.

I started a thread a few weeks ago in Storybook Discord channel to align with the guys on how to reuse certain APIs between builders and I think a few people were mentioning you there. I also looked into Adobe storybook which I think you work on, to see your use-cases (that's the latest one, right? https://github.com/adobe/spectrum-web-components/tree/main/.storybook). Seems like your use-cases should be covered already, but yeah, just let me know what's not working.

Do you maybe want to have a chat or something to discuss the next steps? I'm available in Discord as @bashmish. We can also split the work on this. I plan to finish the work on static build soon. I think one of the next steps is to move it to modern-web and release under `@web`, as well as support MDX and a few other features and do a few changes to Storybook itself to reuse shared APIs. 

PS: I'm in @LarsDenBakker team now together with @thepassle as well, just so that you know :) Lars is saying Hi to you, ha-ha!

**Comment by Westbrook** [comment]
Cool. I'll reach out there. Not sure if I can get any time on the keyboard to build anything here, but am excited to be able to support testing the process if I can. The main feature that we're looking to leverage (beyond what we have now) is federation, we've run into each team having its own "component library" but not having any insight into the larger ecosystem, and while that's possible with the Vite builder, I'm also not excited about adopting new dependencies.

**Comment by Westbrook** [comment]
@bashmish with all the troubles in #2405 where do you think things sit with the builder work you've been up to?

I'd love to get the current release working, but queueing up a 2.0 that moves to Storybook v7 would be a nice next stop...

I try to keep my dev branch up-to-date with it, and right now there only seems to be one issue on the Storybook end of them importing a CJS file incorrectly, which hopefully will be fixed soon.

**Comment by bashmish** [comment]
> I'd love to get the current release working, but queueing up a 2.0 that moves to Storybook v7 would be a nice next stop...

I'm currently very close to making a PR here with latest fixes and updated docs. Hopefully today or tomorrow.

> I try to keep my dev branch up-to-date with it, and right now there only seems to be one issue on the Storybook end of them importing a CJS file incorrectly, which hopefully will be fixed soon.

Can you please give a link to it?

**Comment by bashmish** [comment]
@Westbrook you can review PR :)
