### ISSUE TITLE
[rollup-plugin-html] EJS template tags are mangled

### ISSUE THREAD

**Issue by ecmel** [modernweb-dev/web#2184]
All non html5 tags are escaped and mangled like `<%= var %>` as well as custom tags. Parser should be relaxed.

**Comment by koddsson** [comment]
I think the plugin is working correctly since ` <%= var %>` isn't valid HTML. Maybe you need to run a preprocessor first so that you have valid HTML to run through the plugin.

Custom tags should work. Do you have an example of tags that don't work? And maybe an error, stack trace or reproduction steps?

**Comment by ecmel** [comment]
Custom tags in <head> section does not work but may be that is not needed at all
