### ISSUE TITLE
rollup-plugin-workbox importing wrong rollup-plugin-terser package

### ISSUE THREAD

**Issue by felixapitzsch** [modernweb-dev/web#2261]
I wanted to address this quickly, so, here is the issue instead of a 1-line PR.

https://github.com/modernweb-dev/web/blob/master/packages/rollup-plugin-workbox/src/index.ts line 6 should be:
`import terser from '@rollup/plugin-terser';`
instead of
`import { terser } from 'rollup-plugin-terser';`

The relevant package.json has already been updated the new terser-plugin package, but changing the import statement in index.ts was probably missed.

**Comment by thepassle** [comment]
@koddsson could you take a look? Maybe this has impacted some of the other changes as well?

**Comment by jholt1** [comment]
Same issue for `dev-server-storybook` https://github.com/modernweb-dev/web/blob/master/packages/dev-server-storybook/src/build/rollup/createRollupConfig.ts#L8

**Comment by jholt1** [comment]
Raised a PR for the issue: https://github.com/modernweb-dev/web/pull/2265

**Comment by koddsson** [comment]
> @koddsson could you take a look? Maybe this has impacted some of the other changes as well?

Weird! I thought I had grepped the whole code-base for this, but evidently not. Odd that no build or test failed with this. I'll try to get the PR merged.

**Comment by felixapitzsch** [comment]
> Odd that no build or test failed with this. I'll try to get the PR merged.

It might accidentally work, if some other packages/dependencies are still using the old terser-plugin package as a sub-dependency. As long as it ends up in node_modules, it will be resolved and not raise an error - even, if it is not listed in your package.json anymore.

**Comment by vskorohod** [comment]
Hi.
I have the same issue with the @web/dev-server-storybook plugin. 
```

> build-storybook --output-dir demo-storybook

node:internal/modules/cjs/loader:1029
  throw err;
  ^

Error: Cannot find module 'rollup-plugin-terser'
Require stack:
- /Users/.../node_modules/@web/dev-server-storybook/dist/build/rollup/createRollupConfig.js
- /Users/.../node_modules/@web/dev-server-storybook/dist/build/build.js
- /Users/.../node_modules/@web/dev-server-storybook/dist/build/cli.js
```

Could it be fixed by merging this PR https://github.com/modernweb-dev/web/pull/2265 ?

**Comment by thepassle** [comment]
We have some issues with the CI that we're still investigating. As a temporary workaround you can use a lower version of the plugin.

**Comment by thepassle** [comment]
should be fixed in https://github.com/modernweb-dev/web/pull/2265

**Comment by svanherk** [comment]
It looks like this was fixed as part of [major version bump `v8`](https://github.com/modernweb-dev/web/releases/tag/rollup-plugin-workbox%408.0.0). Is it possible to get this patched for version 7 as well? I'm seeing this error after [this fix in `@open-wc/building-rollup`](https://github.com/open-wc/open-wc/issues/2684), because it is still using `rollup-plugin-workbox` `v7` but has removed `rollup-plugin-terser` as a dependency (exactly the situation mentioned [above](https://github.com/modernweb-dev/web/issues/2261#issuecomment-1537543641)).

I started a PR to update to `rollup-plugin-workbox` `v8`, but there are a lot of changes as a result of moving to workbox 7 that I don't have the context for.  But if that's preferred, I can continue with trying to put up a PR for that in `@open-wc/building-rollup`.
