### ISSUE TITLE
Update @web/dev-server-esbuild dependencie esbuild to v0.21

### ISSUE THREAD

**Issue by mantou132** [modernweb-dev/web#2725]
esbuild v0.21 support javascript decorators, this is useful for testing some decorator-based frameworks

https://github.com/evanw/esbuild/issues/104#issuecomment-2097359571

**Comment by Westbrook** [comment]
Would you be interested in making a contribution with this update?

**Comment by favna** [comment]
From a quick test done by setting esbuild to `~0.21.5` in my package resolutions and nothing breaking outright I think it's as easy as just bumping the dependency and no breaking changes are incurred for web-dev-server but I can't say for sure. 

- v0.20 of esbuild only affects Deno users
- v0.21 is the introduction of decorators and is considered breaking by Evan because when the developer desires the old style decorators implemented by TypeScript they have to add `experimentalDecorators` in their tsconfig (just like they would have to when using TS >5.0)
