### ISSUE TITLE
Legacy Plugin: Unable to load in IE11

### ISSUE THREAD

**Issue by marvinhagemeister** [modernweb-dev/web#450]
I'm trying to get tests to run in IE11, but it fails to load them with the following error message:

<img width="920" alt="Screenshot 2020-08-27 at 11 29 15" src="https://user-images.githubusercontent.com/1062408/91423293-a61e6f80-e858-11ea-853f-52c6e9cafb71.png">

Steps to reproduce:

1. `git clone https://github.com/preactjs/preact`
2. `git checkout wtr`
3. `npm install`
4. `npm run test:wc`
5. Pick any test to focus, press "d" to open the test in a browser and copy the url into IE11

**Comment by LarsDenBakker** [comment]
Thanks for reporting! The issue was that when transforming inline scripts, the filename we give to babel is something like `process.cwd() + '/'` which in the browser maps to `/index.html`. For some reason the created an error in the source maps, but only if you run babel twice (once in legacy and once directly) like in your case.
