### ISSUE TITLE
[browser-logs] print promises

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#543]
Promises logged to the console show up as `{}`. 

We can improve that, at the least we can print `Promise { } `. If possible it would be great to mirror the behavior of the browser/node terminal to also log the Promise status and/or result. I'm not sure if it's possible to get this status synchronously from the promise object.

**Comment by ashikvarma11** [comment]
@LarsDenBakker  I would like to try this one. Please guide me through the process for reproducing this. I'm a beginner.

**Comment by 43081j** [comment]
@ashikvarma11 if you want to pick this up here's my suggested solution:

The browser-logs code really seems to exist so it can copy a logged value (via `console.log`) from the browser session to the test runner:

* Catch all logs
* Serialise each logged value to a string (using [serialize](https://github.com/modernweb-dev/web/blob/1dc41277fd3434120ad4a262e14a80407a2d5dbc/packages/browser-logs/src/serialize.ts#L118))
* Pass the string back to the test runner (through playwright/puppeteer or whatever is used)
* Deserialise the string back to a "fake" object which represents the original one (using [deserialize](https://github.com/modernweb-dev/web/blob/1dc41277fd3434120ad4a262e14a80407a2d5dbc/packages/browser-logs/src/deserialize.ts#L78))

So if you want to print promises nicely, you need to change the serialiser to return something like:

```ts
{ [KEY_WTR_TYPE]: 'Promise' }
```

Just like `undefined` is handled [here](https://github.com/modernweb-dev/web/blob/1dc41277fd3434120ad4a262e14a80407a2d5dbc/packages/browser-logs/src/serialize.ts#L81-L83).

Unfortunately im not aware of a way to check if a promise has resolved or rejected without actually asynchronously catching/then-ing it (which we can't do here because a JSON reviver is synchronous).

Then in the deserialiser you need to add a case to set a fake promise (or something representing one). Just like the one for functions [here](https://github.com/modernweb-dev/web/blob/1dc41277fd3434120ad4a262e14a80407a2d5dbc/packages/browser-logs/src/deserialize.ts#L45-L47):

```ts
case 'Promise':
  return new Promise((res) => { /* implementation hidden */ });
```

it's not great to be generating loads of unresolved promises i suppose. You could also return a `Promise.resolve()` but that may be misleading if what was originally serialised was a rejected promise.

Maybe @LarsDenBakker would be happy with some compromise where we don't make a real promise but just log a string representing one instead, i'm not sure.

**Comment by LarsDenBakker** [comment]
@43081j thanks for the explanation, it's spot on. 

I think for the first version we can start with a compromise - just return `"Promise { }"`. I don't know of any way to synchronously check if a promise is already resolved.. maybe someone knows a trick but we can also add this later. The most important part is communicating that it actually is a promise so that people can know how to proceed with debugging.

**Comment by ashikvarma11** [comment]
@43081j @LarsDenBakker 

I followed the suggestion from @43081j  above and got this result. Would this fix the issue or is there anything else that I'm missing?

`const {deserialize,serialize}  = require('@web/browser-logs');

(async () => `{`
  console.log('normal deserializing ->', JSON.stringify(new Promise((res,rej)=>{})))
  const serialized = serialize(new Promise((res,rej)=>{}))
  const deserialized = deserialize(serialized);
  console.log('web-test-runner deserializing ->',deserialized)
})();`


### Result

```
normal deserializing -> {}
web-test-runner deserializing -> Promise {  }
```


### serialize.js

` if (value instanceof Promise) {

            return { [KEY_WTR_TYPE]: 'Promise' };

        }`

### deserialize.js

```
case 'Promise':
                    // Create a fake new Promise.
                    return `Promise { }`

```

**Comment by 43081j** [comment]
Looks good to me, think its time to open a PR 🥳 

should be easy enough to add a test just like your example if you didn't already too

**Comment by LarsDenBakker** [comment]
Yep that seems good!

**Comment by LarsDenBakker** [comment]
This was implemented
