### ISSUE TITLE
[dev-server] [test-runner] Unable to use @rollup/plugin-babel

### ISSUE THREAD

**Issue by kamil0414** [modernweb-dev/web#840]
`import rollupBabel from '@rollup/plugin-babel';
import { fromRollup } from '@web/dev-server-rollup';

const babel = fromRollup(rollupBabel);

export default {
  plugins: [babel()],
};`

`Error: fromRollup should be called with a rollup plugin function.`

versions:
@web/dev-server-rollup@0.2.10
@rollup/plugin-babel@5.2.1

**Comment by LarsDenBakker** [comment]
The correct syntax should be:

`import { babel as rollupBabel } from '@rollup/plugin-babel';`

This is due to the way the babel plugin is written and compiled.

**Comment by kamil0414** [comment]
Ok, after change I got new error:

`import { babel as rollupBabel } from '@rollup/plugin-babel';
         ^^^^^
SyntaxError: The requested module '@rollup/plugin-babel' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.`

**Comment by LarsDenBakker** [comment]
Ah yes, because your config is node es module you can't import a commonjs module like that. You'd have to write:

```
import * as babelModule from '@rollup/plugin-babel';

const { babel } = babelModule;
```

I think, you'd have to check what that import returns. You can also write the config in commonjs if this is annoying. It's nothing to do with the dev server or test runner, it's just how node js loads modules.

**Comment by web-padawan** [comment]
Closing per above comment as resolved.
