### ISSUE TITLE
[dev-server-rollup] fails to load certain commonjs modules

### ISSUE THREAD

**Issue by LarsDenBakker** [modernweb-dev/web#873]
As reported by a user on slack, some requests fail to load. See a reproduction here: https://github.com/zenwork/webdevsserver-issue

**Comment by stephenwade** [comment]
I can reproduce this in the dev-server-rollup repo. Upgrade @rollup/plugin-commonjs to v16 and the tests hang.

Comment out the following two lines to avoid the problem:
https://github.com/modernweb-dev/web/blob/97f11395a91f7330faccd80e4e1418c0e2166c38/packages/dev-server-rollup/test/node/fixtures/commonjs/commonjs-browser-test.js#L11-L12

**Comment by stephenwade** [comment]
The issue is in the plugin - this promise never resolves:
```js
// rollup/plugins/packages/commonjs/src/proxies.js#L53
const isCjs = await getIsCjsPromise(id);
```
https://github.com/rollup/plugins/blob/f11bc386e1fd72a9fd51f9cc6c3ba9c54487fe61/packages/commonjs/src/proxies.js#L53

It looks like the `moduleParsed` hook is never being called, and that's where the promise is resolved.

I would open an issue in the Rollup repo, but I can't figure out how to create a minimal example. When I tried to recreate the test on my own, it worked just fine. You can see my test here:
https://github.com/stephenwade/rollup-plugin-issue-repro

**Comment by LarsDenBakker** [comment]
You're right it was never called. It was added relatively recently, and we didn't implement it. I added it now in https://github.com/modernweb-dev/web/pull/886
